### ISSUE TITLE
Permission denied when cloning from PokemonGo-Bot

### ISSUE THREAD

**Issue by fredrik-hellmangroup** [OpenPoGo/OpenPoGoWeb#10]
D:\Pokemon stuff\PokemonGo-Bot>git submodule update --init --recursive
Cloning into 'web'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:OpenPoGo/OpenPoGoWeb.git' into submodule path 'web' failed

**Comment by Diskmaster** [comment]
The correct clone url is https://github.com/OpenPoGo/OpenPoGoWeb.git
