### ISSUE TITLE
Show Pokemon HP in Pokemon list?

### ISSUE THREAD

**Issue by BobbyWibowo** [OpenPoGo/OpenPoGoWeb#107]
Feature request. Pretty sure this hasn't been implemented yet, right?

**Comment by RolfKoenders** [comment]
Nice request! I was about to create the same issue!

This data is available. The properties `pokemon_data.stamina` & `pokemon_data.stamina_max` are available to make a [progressbar](http://materializecss.com/preloader.html).

I will try to take a look at this. 

Created PR: #109

**Comment by JulianMBr** [comment]
This is a duplicate and PR is in discussion. Follow #109 and add your input there ;-) Much appreciated!
