### ISSUE TITLE
candy/pokedex issue with dev branch of the bot

### ISSUE THREAD

**Issue by w1sht0l1v3** [OpenPoGo/OpenPoGoWeb#110]
on the dev branch of the bot candy says it's undefined and pokedex isn't loading anything...

```
TypeError: self.pokemonArray[(pkmID - 1)] is undefined
mapView.sortAndShowPokedex() main.js:615
mapView.buildMenu() main.js:328
mapView.bindUi/<() main.js:180
n.event.dispatch() jquery.min.js:3
n.event.add/r.handle() jquery.min.js:3
```

there's also some socket error:
`GET XHR http://192.168.0.4/socket.io/                  [HTTP/1.1 404 Not Found 2ms]`

**Comment by knobunc** [comment]
The candy error is because the web is looking for pokemon_family and the bot is writing candy.  Change main.js to look for candy and it is fixed.

**Comment by knobunc** [comment]
Here's the candy fix: https://github.com/OpenPoGo/OpenPoGoWeb/pull/98

**Comment by JulianMBr** [comment]
As soon the pull for #98 is approved, this should be fixed.
