### ISSUE TITLE
Trainer Icon Not Showing

### ISSUE THREAD

**Issue by afuzha** [OpenPoGo/OpenPoGoWeb#115]
i have latest git pull, but why my trainer icon not showing? it just show path... and pokemon candy still undefined? need help :) thank you...

![capture](https://cloud.githubusercontent.com/assets/4647602/17236277/1016b8b2-5572-11e6-8a2c-196458ad7fae.PNG)

**Comment by talmachani** [comment]
missing "./" in images path in main js
