### ISSUE TITLE
Remove Trainer Icons

### ISSUE THREAD

**Issue by Chrischi-** [OpenPoGo/OpenPoGoWeb#117]
Remove Trainer Icons and use eg Pokéballs with random colors as trainer icon.

It requires only one icon or we could do it alone with CSS instead.

We could place a 'label' or 'hover' over the icon to identify which trainer we are looking at.

**Comment by Chrischi-** [comment]
it would look like this

![map](https://cloud.githubusercontent.com/assets/6323217/17250405/80474af2-55a4-11e6-94c8-96d7768c6337.jpg)
#122

**Comment by Chrischi-** [comment]
I used a quick and dirty code edit to test it.

It's not multi-user applicable.

Icon: 
![pokeball](https://cloud.githubusercontent.com/assets/6323217/17250547/12938768-55a5-11e6-8e86-f6c05b40a2d7.png)
(doesnt know the creator...)

```
main.js

   user_data[users[user_index]].marker = new google.maps.Marker({
      map: map,
      position: {lat: parseFloat(data.lat), lng: parseFloat(data.lng)},
      //icon: 'image/trainer/' + trainerSex[randomSex] + Math.floor(Math.random() * numTrainers[randomSex]) + '.png',
      icon: 'image/trainer/pokeball.png',
      zIndex: 2,
      //label: users[user_index]
    });
```

**Comment by BobbyWibowo** [comment]
I did something like this. Multi-bots shouldn't cause much issue, considering the Find button works just fine.
![trainer_icon](https://cloud.githubusercontent.com/assets/9364930/17251147/b928bffe-55d1-11e6-9a89-f89a9128aacd.png)
