### ISSUE TITLE
Error 404 location-xxxjson

### ISSUE THREAD

**Issue by ghost** [OpenPoGo/OpenPoGoWeb#120]
127.0.0.1 - - [29/Jul/2016 10:11:09] code 404, message File not found
127.0.0.1 - - [29/Jul/2016 10:11:09] "GET /location-xxxx@gmail.com.json HTTP/1.1" 404 -

other files ok

**Comment by arckosfr** [comment]
Same Here :/

**Comment by bbaret** [comment]
Do you have this file in the web folder ? If not, try to create create it manually.

**Comment by arckosfr** [comment]
No, and yes if i create manually it work.
But don't have the path of the bot on maps (only the trainer icon and he move)

**Comment by ghost** [comment]
thanks @arckosfr
