### ISSUE TITLE
Use Pokemon Go Map Colors

### ISSUE THREAD

**Issue by Chrischi-** [OpenPoGo/OpenPoGoWeb#122]
I changed the Google Maps Style to reflect a more PGo like style.

```
  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 50.0830986, lng: 6.7613762},
    zoom: 8,
    mapTypeId: 'roadmap',
          styles: [ 
          { "featureType": "road", "elementType": "geometry.fill", "stylers": [ { "color": "#4f9f92" }, { "visibility": "on" } ] },
          { "featureType": "water", "elementType": "geometry.stroke", "stylers": [ { "color": "#feff95" }, { "visibility": "on" }, { "weight": 1.2 } ] },
          { "featureType": "landscape", "elementType": "geometry", "stylers": [ { "color": "#adff9d" }, { "visibility": "on" } ] },
          { "featureType": "water", "stylers": [ { "visibility": "on" }, { "color": "#147dd9" } ] },
          { "featureType": "poi", "elementType": "geometry.fill", "stylers": [ { "color": "#d3ffcc" } ] },{ "elementType": "labels", "stylers": [ { "visibility": "off" } ] } 
          ]
  });
```

This is how it looks:
![map](https://cloud.githubusercontent.com/assets/6323217/17250074/08b44b30-55a3-11e6-8196-25fb728a4313.jpg)

I think this should be implemented

;) uhhh, look at the little wiener-street they build

**Comment by BobbyWibowo** [comment]
That pokemon ball, is that the trainer icon?

**Comment by Chrischi-** [comment]
@BobbyWibowo 
Yes it is... i opened another issue to use pokeballs with different colors instead of the many trainer icons. Issue #117

**Comment by BobbyWibowo** [comment]
Mind sharing your icon? I have salvaged pull requests here and there for my own local copies and I'd love to use that icon as well, lol

**Comment by Chrischi-** [comment]
@BobbyWibowo 
nope, but this is the wrong issue to talk about it.

i updated #117 with a quick & dirty test.

**Comment by BoGnY** [comment]
Very very wonderful enhancement!! :)

**Comment by jadbalout** [comment]
Made it a pull request. This looks nice.

**Comment by TridentNooch** [comment]
Yeah the downside of doing this is for those of us who don't want the Pokemap colors there is no way to change it back to standard google in the interface.  

For me I had to compare the lines of code and remove this so I could see road names and what not. When you live in a populated area that's crucial.

**Comment by kazyka** [comment]
implemented

**Comment by Chrischi-** [comment]
BobbyWibowo did a nice job on his own repository. He implemented it into the config.js and you can change if you want the full Pokemon experience or the normal Google Maps.

@BobbyWibowo could you do a pull request for this?

**Comment by BobbyWibowo** [comment]
@Chrischi- I'll have to make another branch with that particular customization only since my repo has lots of other changes (and my repo is based on wchill/refactor branch instead of main). And I'm honestly too lazy, but oh well, I'll try to do it in a few hours or so, lol

**UPDATE:** #143
