### ISSUE TITLE
Pokedex issue on the dev branch of the bot..

### ISSUE THREAD

**Issue by knobunc** [OpenPoGo/OpenPoGoWeb#123]
pokedex isn't loading anything...

TypeError: self.pokemonArray[(pkmID - 1)] is undefined
mapView.sortAndShowPokedex() main.js:615
mapView.buildMenu() main.js:328
mapView.bindUi/<() main.js:180
n.event.dispatch() jquery.min.js:3
n.event.add/r.handle() jquery.min.js:3

[Spun off from another issue that had the candy bug too]

**Comment by tim427** [comment]
Easy to fix:

Replace on line 614:
"pkmID = pokedex_entry.pokedex_entry_number," with;
"pkmID = pokedex_entry.pokemon_id,"

Will create pull request later on!

**Comment by kazyka** [comment]
fixed https://github.com/OpenPoGo/OpenPoGoWeb/pull/125
