### ISSUE TITLE
How to git pull

### ISSUE THREAD

**Issue by ghost** [OpenPoGo/OpenPoGoWeb#131]
I use PokemonGo-Bot [https://github.com/PokemonGoF/PokemonGo-Bot/](url) dev but web interface not  upgrade.
How I upgrade?

**Comment by RolfKoenders** [comment]
Its actually in the documentation of [OpenPoGoWeb](https://github.com/OpenPoGo/OpenPoGoWeb#installation-and-use)

In the directory of PokemonGo-Bot run this:

```
$ git submodule foreach git pull origin master
```

This will pull master of the submodules.
