### ISSUE TITLE
404 message File not found

### ISSUE THREAD

**Issue by ghost** [OpenPoGo/OpenPoGoWeb#132]
Please help me, this is error.
http://i.imgur.com/NJMFHdW.png

127.0.0.1 - - [30/Jul/2016 11:13:53] code 404, message File not found
127.0.0.1 - - [30/Jul/2016 11:13:53] "GET /socket.io/?EIO=3&transport=polling&t=LOy9tC0 HTTP/1.1" 404

**Comment by ultiferrago** [comment]
I am looking into fixing this now. I will submit a PR for it when done.

**Comment by ghost** [comment]
You need more information?

**Comment by Rlewisrlou666** [comment]
Same problem here I'll keep an eye on this thread.

**Comment by wchill** [comment]
This is not a problem with this repo. We are no longer supporting `SimpleHTTPServer`, as https://github.com/OpenPoGo/OpenPoGoBot already loads a web server that is Socket.io capable.

**Comment by ghost** [comment]
Flask? Please help me run this page.
