### ISSUE TITLE
[IDEA] Separate each account to specific URL

### ISSUE THREAD

**Issue by felixzzz** [OpenPoGo/OpenPoGoWeb#14]
provide each url for each account
so for example my private url will be

localhost:8000/view/felix@salim.bz => or else instead of put it all together, we could separate it.

It's also cool so show all but maybe using different url

localhost:8000/view/all (maybe some privileged needed.

Sorry I couldn't contribute for now, but here's some idea that might be useful :)

**Comment by sniok** [comment]
I personally like to watch all my bots together

**Comment by wchill** [comment]
Not necessary since we're going to use an options panel to toggle accounts on and off.
