### ISSUE TITLE
The bot was working fine...but then I got an error. Broken pipe?

### ISSUE THREAD

**Issue by SaipanDamashii** [OpenPoGo/OpenPoGoWeb#152]
It was catching the pokemon, and then I decided to reload the web page to see if it would update my location and show my trainer (see my other issue)....and then this happened after the Web client connected message popped up.

> [2016-07-31 17:27:55] [Catch] A wild Machop appeared! [CP 321] [Potential 0.71]
> [2016-07-31 17:27:59] [Catch] Using Greatball... (71 left!)
> [2016-07-31 17:27:59] [Catch] Machop has been caught! (CP 321, IV 0.71)
> [2016-07-31 17:27:59] [Catch] Rewards: 210 XP, 100 Stardust, 3 Candy
> [2016-07-31 17:28:59] Web client connected
> Exception in thread Thread-854:
> Traceback (most recent call last):
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in **bootstrap_inner
>     self.run()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 602, in process_request_thread
>     self.handle_error(request, client_address)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init**
>     self.finish()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
>     self.wfile.close()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
>     self.flush()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe

**Comment by wchill** [comment]
Broken pipe is fine; it just means your browser disconnected.
