### ISSUE TITLE
SocketIO server

### ISSUE THREAD

**Issue by ghost** [OpenPoGo/OpenPoGoWeb#153]
I try use nginx in fedora24.
I install nginx normaly, 
and run in /home/carlos/Documentos/POKEMON/PokemonGo-Bot
git clone https://github.com/OpenPoGo/OpenPoGoWeb web

```
        ----| nginx.conf |----
```

`server {`
`listen       5000 default_server;`
`listen       [::]:5000 default_server;`
`listen       80   default_server;`
`listen       [::]:80   default_server;`
`server_name  _;`
`#        root         /usr/share/nginx/html;`
`root          /home/carlos/Documentos/POKEMON/PokemonGo-Bot/web;`
----| end nginx.conf |----
----| log/error.log |----
2016/07/31 12:48:14 [error] 4195#0: *1 open() "/usr/share/nginx/www/OpenPoGoWeb/404.html" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /socket.io/?EIO=3&transport=polling&t=LP1f34q HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2016/07/31 12:48:19 [error] 4195#0: *1 "/usr/share/nginx/www/OpenPoGoWeb/socket.io/index.php" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /socket.io/?EIO=3&transport=polling&t=LP1f4JX HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2016/07/31 12:48:19 [error] 4195#0: *1 open() "/usr/share/nginx/www/OpenPoGoWeb/404.html" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /socket.io/?EIO=3&transport=polling&t=LP1f4JX HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2016/07/31 12:48:24 [error] 4195#0: *1 "/usr/share/nginx/www/OpenPoGoWeb/socket.io/index.php" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /socket.io/?EIO=3&transport=polling&t=LP1f5Xu HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2016/07/31 12:48:24 [error] 4195#0: *1 open() "/usr/share/nginx/www/OpenPoGoWeb/404.html" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /socket.io/?EIO=3&transport=polling&t=LP1f5Xu HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2016/07/31 12:48:29 [error] 4195#0: *3 "/usr/share/nginx/www/OpenPoGoWeb/socket.io/index.php" is not found (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /socket.io/?EIO=3&transport=polling&t=LP1f6mE HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"
2016/07/31 12:48:29 [error] 4195#0: *3 open() "/usr/share/nginx/www/OpenPoGoWeb/404.html" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /socket.io/?EIO=3&transport=polling&t=LP1f6mE HTTP/1.1", host: "127.0.0.1", referrer: "http://127.0.0.1/"

**Comment by BobbyWibowo** [comment]
It simply couldn't find a 404.html (which it doesn't ship by default as it's not necessary anyway). As for socket.io/index.php, that has something to do with the new WebSocket feature. I don't know much about this, but if you use OpenPoGoBot, it's supposed to run a SocketIO server.

**Comment by ghost** [comment]
Please help me how to run SocketIO server?

**Comment by wchill** [comment]
We do not support PokemonGo-Bot. OpenPoGoBot runs its own web server internally and no additional configuration is needed.

**Comment by ghost** [comment]
Yes. In config json.
