### ISSUE TITLE
Don't use setInterval to update user data

### ISSUE THREAD

**Issue by octa7th** [OpenPoGo/OpenPoGoWeb#155]
Using `setInterval` to fetch user data from Ajax is bad practice. We cannot assume one request will be finished before next request is called. The problem will likely appear when user have a bad internet connection or server in a high load.

![screenshot from 2016 08 01 09 51 27](https://cloud.githubusercontent.com/assets/2761140/17282307/b203970e-57ce-11e6-91be-2e82e8af34da.png)

The solution is waiting for the Ajax request to complete and then call the next one. We can use `Promise` to help us implement this.

**Comment by BobbyWibowo** [comment]
[wchill/refactor](https://github.com/OpenPoGo/OpenPoGoWeb/tree/wchill/refactor) branch uses [bluebird Promise](http://bluebirdjs.com/docs/api/new-promise.html) to handle JSON loads. It's currently under development, but I heard it'll be the main focus.

**Comment by octa7th** [comment]
Sorry, I didn't check that branch yet.
