### ISSUE TITLE
Maintainers, where are you ?

### ISSUE THREAD

**Issue by aslafy-z** [OpenPoGo/OpenPoGoWeb#177]
Please merge pull requests guys !

**Comment by BobbyWibowo** [comment]
Probably still kinda occupied with the bots due to the new API finally working. Probably.

**Comment by aslafy-z** [comment]
Mmh, PokemonGoF/PokemonGo-Bot is working tho

**Comment by glenncampioni** [comment]
I'm afraid this fork is slowly dying. It's been 6 days since the last PR was merged in this web project.
I'll be focusing my development on the original PokemonGoF/PokemonGo-Bot fork.

**Comment by aslafy-z** [comment]
This is the official map implementation for PokemonGoF/PokemonGo-Bot (i am wrong ?), it souldn't be dying ...

**Comment by BobbyWibowo** [comment]
pst my fork is still being updated

**Comment by BobbyWibowo** [comment]
@aslafy-z PokemonGoF has a fork of this repo here: https://github.com/PokemonGoF/PokemonGo-Web way less activity than here tho imo

**Comment by MaxLeiter** [comment]
A few of us (primarily @wchill and I) were busy working on Unknown6, were back now and will behind reviewing ASAP

**Comment by MaxLeiter** [comment]
Also, we're currently working on refactoring https://github.com/OpenPoGo/OpenPoGoUI as an alternative to this web UI. It's likely we'll merge current PRs, but the majority of our effort won't be on this repo.

**Comment by glenncampioni** [comment]
Hadn't even noticed that yet. Web sockets are far better than reading json files.
Nice work!

**Comment by jtdroste** [comment]
I'd also like to check in. I was at a conference the past few days
