### ISSUE TITLE
Record starting point and end point for a path

### ISSUE THREAD

**Issue by SamuilDichev** [OpenPoGo/OpenPoGoWeb#18]
I have an enhancement proposal. The bot outputs in the logs the start and end points when the trainer travels, so it shouldn't be too hard to draw a predicted path on the map for some visual feedback of where the trainer is traveling next. It would also be nice to record the last X points of travel and the path between them. I think it would help botters optimize their bots.

Thanks

**Comment by Reaver01** [comment]
This feature will be added in the next patch.  If you would like to preview it now please see https://github.com/OpenPoGo/OpenPoGoWeb/tree/patch

**Comment by SamuilDichev** [comment]
Thanks.
