### ISSUE TITLE
how does the multibot support work

### ISSUE THREAD

**Issue by ckrmml** [OpenPoGo/OpenPoGoWeb#19]
i can only see the stats from one of my bots. so how does it work here? i must be too stupid to get it.
reverted back to sniok https://github.com/OpenPoGo/OpenPoGoWeb/commit/33cbeb110151f53bff126e2b7f7da0125ed3203e

**Comment by alexanderrock** [comment]
I've started 4 bots and started the map.
All 4 are displayed but i have to manually zoom to them, under the Trainer" section it should defineable which one to follow and also in the config of the "web" define a start/default trainer to follow

**Comment by glenncampioni** [comment]
The current code only pans the map if there's just one user (bot) defined.

> if (users.length === 1 && userFollow === true) {
>     map.panTo({
>       lat: parseFloat(data.lat),
>       lng: parseFloat(data.lng)
>     });
>   }

It wouldn't be too hard to track the bot you click on in the dropdown to the right.

**Comment by Reaver01** [comment]
It does however, pan to whatever pokemon show up, which is only an issue if the pokemon show up at the same time I guess.

**Comment by Reaver01** [comment]
There is now an option to zoom in on bot of choice
