### ISSUE TITLE
gym info on map

### ISSUE THREAD

**Issue by nowak-mateusz** [OpenPoGo/OpenPoGoWeb#20]
I write additional info on gyms about pokemons in. Now when you separate web I don know how to PR that. https://github.com/nowak-mateusz/PokemonGo-Bot/commit/51ab4066532ce13a79ec1e42f8db50c4c573f8b2
Now I go sleep :P

**Comment by Reaver01** [comment]
PR the js to https://github.com/OpenPoGo/OpenPoGoWeb/tree/patch
PR the py to https://github.com/nowak-mateusz/PokemonGo-Bot

**Comment by nowak-mateusz** [comment]
ok I wait for PR https://github.com/PokemonGoF/PokemonGo-Bot/pull/800
