### ISSUE TITLE
Use Flask backend + WebSockets instead of loading JSON from file

### ISSUE THREAD

**Issue by wchill** [OpenPoGo/OpenPoGoWeb#26]
Contingent on https://github.com/OpenPoGo/OpenPoGoBot/pull/55.

Web component should use Flask and install a listener for when relevant bot events are fired.

Instead of AJAXing JSON from disk every second, WebSockets should be used.

**Comment by Saturate** [comment]
WebSockets would be a very nice solution.

**Comment by meyer9** [comment]
Done in #69
