### ISSUE TITLE
No Image or Menu For Trainers?

### ISSUE THREAD

**Issue by dotaxis** [OpenPoGo/OpenPoGoWeb#31]
My map shows Pokemon when they appear but I have no menu to show stats for trainers and they also don't appear on the map.

![screen shot 2016-07-25 at 4 35 39 am](https://cloud.githubusercontent.com/assets/11805686/17098739/4951fc9e-5221-11e6-804d-30f9b5017db0.png)

**Comment by sniok** [comment]
Make sure to properly edit userdata.js

**Comment by dotaxis** [comment]
I have. And like I said it pans to the player and shows Pokemon sprites when the bot finds one. I would think that makes it obvious that my userdata.js is proper.

**Comment by sniok** [comment]
Provide more information to reproduce the bug. What version are you using, is there a location-YOURNAME.json file, what is the output in DevTools console.

**Comment by dotaxis** [comment]
Just cloned from master branch. There's no location-***.json.

DevTools console is throwing 404's for location-botname.json and catchable-botname.json.

**Comment by sniok** [comment]
Webview should be located in web/ folder inside main bot folder

**Comment by dotaxis** [comment]
That's where it is. Apparently not a 404 though, it was scrolling fast so I didn't get a great look.

`main.js:367 XMLHttpRequest cannot load file:///Users/dotaxis/Pokemon.GO.Hacks/pogo/web/catchable-*****.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.loadJSON @ main.js:367addCatchable @ main.js:326
main.js:182 XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: ""…}errorFunc @ main.js:182xhr.onreadystatechange @ main.js:362loadJSON @ main.js:367addCatchable @ main.js:326`

**Comment by sniok** [comment]
You should run `python -m SimpleHTTPServer` instead of just opening index.html

**Comment by dotaxis** [comment]
It appears OpenPoGoWeb doesn't work with PokemonGo-Bot. Only OpenPoGoBot.

The repo for PokemonGo-Bot links here so I didn't think about that. Works fine with OpenPoGoBot.

**Comment by Reaver01** [comment]
@dotaxis if you use PokemonGo-Bot you have to create the location-trainername.json file yourself right now.. it only writes to that file if it already exists for some reason.
