### ISSUE TITLE
Change some icons more clearer 

### ISSUE THREAD

**Issue by qfdk** [OpenPoGo/OpenPoGoWeb#44]
I put the original file "PNG" in my site 
[Download here](http://qfdk.me/imgs.zip)
![qq20160721-0 2x](https://cloud.githubusercontent.com/assets/2404478/17038440/035bbaf0-4f96-11e6-8b64-d49f9f96da32.png)

**Comment by jtdroste** [comment]
Interesting!  Can you give a estimate of the average filesize of one of these new images?  I'm on terribly slow hotel wifi, so I can't download it right now.

**Comment by meyer9** [comment]
I'd like to see this implemented.

**Comment by Alcazer** [comment]
in main.js line 281

> https://github.com/OpenPoGo/OpenPoGoWeb/blob/master/main.js#L281
> `icon: 'image/pokemon/' + pad_with_zeroes(data.pokemon_id, 3) + imageExt,`
> change
> `icon: {url:'image/pokemon/' + pad_with_zeroes(data.pokemon_id, 3) + imageExt, scaledSize: new google.maps.Size(70, 70)},`

and

in main.js line 299

> https://github.com/OpenPoGo/OpenPoGoWeb/blob/master/main.js#L299
> `user_data[users[user_index]].catchables[data.spawnpoint_id].setIcon('image/pokemon/' + pad_with_zeroes(data.pokemon_id, 3) + imageExt);`
> change
> `user_data[users[user_index]].catchables[data.spawnpoint_id].setIcon({url:'image/pokemon/' + pad_with_zeroes(data.pokemon_id, 3) + imageExt, scaledSize: new google.maps.Size(70, 70)});`

and 

in main.css line 50

> https://github.com/OpenPoGo/OpenPoGoWeb/blob/master/main.css#L50
> `.png_img {
>     width: 96px;
>     height: auto;
> }`
> change
> `.png_img {
>     width: 96px;
>     height: 96px;
> }`

last

change imgs folder name to pokemon
then dont forget add zero like (1.png -> 001.png)

or change all
`pad_with_zeroes(data.pokemon_id, 3) + imageExt`
to
`data.pokemon_id + '.png'`

**Comment by Reaver01** [comment]
I will just batch rename the files

**Comment by Reaver01** [comment]
No need to change Js for images.

**Comment by Alcazer** [comment]
new images are big, this js commands scale new images

old images sizes 96x96
new images sizes 120x120 (some 126x120, 144x120, 148x120, 150x120, 158x117) 

or resize all images

**Comment by RedSparr0w** [comment]
Yeah the new images will just need to be scaled a bit, as they appear quite large on the map.

i dont think we should put 

``` css
.png_img {
    width: 96px;
    height: 96px;
}
```

as some of the images are not square (such as Golbat) and will be distorted

edit: unless we batch process them to all be square?
edit 2: Only the following are not 120x120

```
144
131
006
018
022
042
142
146
103
```

**Comment by RedSparr0w** [comment]
Think this can be closed now.
