### ISSUE TITLE
Having issues with userdata.js

### ISSUE THREAD

**Issue by endeavor7** [OpenPoGo/OpenPoGoWeb#50]
Account is a google account.  Let's call it ABC123@gmail.com.

In userdata.js, I modified line 3 to try both:

var users = [ABC123@gmail.com];

and

var users = ["ABC123@gmail.com"];

I also included my API key.

When running python -m SimpleHTTPServer, I get:

127.0.0.1 - - [25/Jul/2016 20:45:47] code 404, message File not found
127.0.0.1 - - [25/Jul/2016 20:45:47] "GET /catchable-username.json HTTP/1.1" 404 -
127.0.0.1 - - [25/Jul/2016 20:45:47] code 404, message File not found
127.0.0.1 - - [25/Jul/2016 20:45:47] "GET /location-username.json HTTP/1.1" 404 -

I looked in the main.js and even commented out the lines where it looks for 

loadJSON('location-' + users[i] + '.json', trainerFunc, errorFunc, i);

and hardcoded 

loadJSON('location-ABC123@gmail.com.json', trainerFunc, errorFunc, i);

to no avail.  It still looks for location-username.json.  

Any help as to what is causing my error?

**Comment by maestroi** [comment]
@endeavor7 
please do the following steps:
1. Navigate to the OpenPoGoBot  folder.
2. Open a file and put in `{}`.
3. Save the file as `catchable-abc123@gmail.com.json`.
4. Restart webservice.

Repeat steps for location.json:
1. Navigate to the OpenPoGoBot  folder.
2. Open a file and put in `{}`.
3. Save the file as `location-abc123@gmail.com.json`.
4. Restart webservice.

**Comment by RedSparr0w** [comment]
Probably loading a cached version of main.js
Try disable the cache and see what happens.

ps: this is the correct one to use in userdata.js:

``` javascript
var users = ["ABC123@gmail.com"];
```

**Comment by endeavor7** [comment]
The cached version was the problem! Thanks for clearing this up.

**Comment by gregtampa** [comment]
how can you delete the cache?

**Comment by delrio1110** [comment]
how can you delete the cache?

**Comment by BobbyWibowo** [comment]
They meant the main.js file was cached on your browser (cached userdata.js should be the main cause though). Just hard refresh the page. Ctrl+F5 will do on most dekstop browsers.
