### ISSUE TITLE
Pokemon sort by candies

### ISSUE THREAD

**Issue by phpfelipe** [OpenPoGo/OpenPoGoWeb#55]
Implementation in sort, most candies.

**Comment by Reaver01** [comment]
I was working on this earlier but kept running into errors. @particle6 I think I have become stupid with your amazing refactor.

**Comment by particle6** [comment]
@Reaver01 I can take a look at this as well.

**Comment by jadbalout** [comment]
https://github.com/OpenPoGo/OpenPoGoWeb/pull/140
Added.
