### ISSUE TITLE
[bug] Sort menu stays on "Info" view

### ISSUE THREAD

**Issue by RedSparr0w** [OpenPoGo/OpenPoGoWeb#60]
#### Bug:

Sort buttons stay on player info window after viewing pokemon or pokedex
![](https://i.imgur.com/NY6Xo4w.png)
#### Steps to reproduce:
1. Open Pokemon Window
2. Click Info
#### Expected Outcome:

Sort buttons disappear.
#### Actual Outcome:

Sorting buttons stay.

_would have fixed it but ran out of time tonight, sorry._

**Comment by Reaver01** [comment]
What branch

**Comment by Reaver01** [comment]
Fixed
