### ISSUE TITLE
Error while using the map with PokeGO- Bot

### ISSUE THREAD

**Issue by AndreAbdel27** [OpenPoGo/OpenPoGoWeb#73]
C:\Users\Andrea\Desktop\PokemonGo-Bot-master\OpenPoGoWeb-master>python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
127.0.0.1 - - [26/Jul/2016 23:30:28] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2016 23:30:28] "GET /css/main.css HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2016 23:30:28] "GET /config/userdata.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2016 23:30:28] "GET /js/main.js HTTP/1.1" 200 -
127.0.0.1 - - [26/Jul/2016 23:30:28] code 404, message File not found
127.0.0.1 - - [26/Jul/2016 23:30:28] "GET /favicon.ico HTTP/1.1" 404 -
I dont have any file "favicon.ico"... any help?

**Comment by kjagiello** [comment]
That request is automatically issued by you browser in order to display the tab icon/the icon next to the URL in the address bar. This project does not provide any favicon, thus the 404. Nothing to worry about.

**Comment by Reaver01** [comment]
There is no favicon for this project.
