### ISSUE TITLE
allow choosing Info/Items etc... by user

### ISSUE THREAD

**Issue by talmachani** [OpenPoGo/OpenPoGoWeb#79]
When using putting ultipal users in userdata.js
it only show the data for da last user on the list

**Comment by Reaver01** [comment]
Please confirm that you are adding a second user like the example below:  

``````
// MUST CONFIGURE THE USER ARRAY AND GOOGLE MAPS API KEY.
// YOU CAN GET A KEY HERE: https://developers.google.com/maps/documentation/javascript/get-api-key
var userInfo = {
    users: ["username", "username2"],
    userZoom: true,
    userFollow: true,
    gMapsAPIKey: "YOUR_API_KEY_HERE"
};```
``````

**Comment by talmachani** [comment]
Did this and got 

// MUST CONFIGURE THE USER ARRAY AND GOOGLE MAPS API KEY.
// YOU CAN GET A KEY HERE: https://developers.google.com/maps/documentation/javascript/get-api-k
var userInfo = {
         users : ["user1@emal.com","user2@emal.com","user3@emal.com"],
         userZoom : true,
         userFollow : true,
         imageExt : ".png",
         gMapsAPIKey : "somkeKEY"
};

ok idid that and now  i get 

gMapsAPIKey is not defined(anonymous function) @ main.js:70i @ jquery.min.js:2j.fireWith @ jquery.min.js:2n.extend.ready @ jquery.min.js:2K @ jquery.min.js:2

**Comment by Reaver01** [comment]
// MUST CONFIGURE THE USER ARRAY AND GOOGLE MAPS API KEY.
// YOU CAN GET A KEY HERE: https://developers.google.com/maps/documentation/javascript/get-api-k
