### ISSUE TITLE
Sort by doesnt work correctly

### ISSUE THREAD

**Issue by JulianMBr** [OpenPoGo/OpenPoGoWeb#80]
When sorting e.g. for "IV" or for "CP" numbers above 1000 will actually be counted smaller as 900.
It sorts after 9,8,7,6,5,4,3,2,1 rather than taking the real amount into consideration.

![openpogo web ui](https://cloud.githubusercontent.com/assets/1734844/17171366/b6ed4850-53f0-11e6-8c54-1b881f097f46.png)

**Comment by Reaver01** [comment]
In all of my tests I have never had it do that.  Please provide more info.  OS/Browser/branch/commit/bot using
