### ISSUE TITLE
Don't display items with count=0

### ISSUE THREAD

**Issue by Nihisil** [OpenPoGo/OpenPoGoWeb#81]
I think it will be nice to hide them.

![openpogo web ui 2016-07-27 6 pm-27-57](https://cloud.githubusercontent.com/assets/475367/17172479/e7c8884a-5427-11e6-932b-d0a463e3137b.png)

**Comment by Reaver01** [comment]
It looks like I need to fix item count.  I will do both.

**Comment by wchill** [comment]
Closed by #113.
