### ISSUE TITLE
Progress bar for experience is wrong

### ISSUE THREAD

**Issue by Nihisil** [OpenPoGo/OpenPoGoWeb#83]
![openpogo web ui 2016-07-27 8 pm-43-01](https://cloud.githubusercontent.com/assets/475367/17175568/d87af54a-543a-11e6-994d-160f9f12ac8f.png)

I'm in the beginning of 23 level, only 15-20% completed.

But in the trainer info progress bar indicate that I'm almost finished the level.

**Comment by BobbyWibowo** [comment]
I had no idea whether the data for "current exp to level up" was available, so I made an array of required exp to level up based on the chart here: http://www.ign.com/wikis/pokemon-go/How_to_Level_Up_Your_Trainer#Level_Experience_Chart. After that, it's just simple calculations.
![pokego-bot-trainer-info](https://cloud.githubusercontent.com/assets/9364930/17230459/7a7b80ec-5546-11e6-9456-3311769c5683.png)

**Comment by BobbyWibowo** [comment]
#126 a PR was made to solve this issue (not mine)

**Comment by Nihisil** [comment]
@BobbyWibowo thanks, it is perfect. I hope it will be merged :)

**Comment by BobbyWibowo** [comment]
The PR was merged, this issue can be closed.
