### ISSUE TITLE
Not understand how to run... any full commend 

### ISSUE THREAD

**Issue by NeoVilsonWong** [OpenPoGo/OpenPoGoWeb#85]
Not understand how to run... any full commend ?

and 

If you want to serve this as a webpage you will have to set up a webserver, for example:

```
$ cd OpenPoGoBot\web  
$ python -m SimpleHTTPServer
```

inside pokemongobot\web i cant see any "SimpleHTTPServer"

**Comment by particle6** [comment]
SimpleHTTPServer is part of python. You should be able to run that line from within the web dir.

https://docs.python.org/2/library/simplehttpserver.html
