### ISSUE TITLE
Capturing less pokemon?

### ISSUE THREAD

**Issue by Witzbold** [OpenPoGo/OpenPoGoWeb#87]
As far as I can tell, it seem like the new version of the bot (current dev) is capturing less pokemon than the version I used yesterday. This is just an impression and I have no exact numbers.
Is anyone experiencing the same problem?

My settings are:
    "catch": {
      "any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"}
    }

**Comment by Saturate** [comment]
Wrong repo :)

**Comment by BoGnY** [comment]
Settings are correct...
Pokemon appeared depends from niantic server, the bot catch correctly all that appear??

However, this repo is for web-gui and NOT for bot..
This is the correct repo link: [https://github.com/PokemonGoF/PokemonGo-Bot/](url)

**Comment by Witzbold** [comment]
oh sorry yes my fault ty but yes it does catch all that appear
