### ISSUE TITLE
Edit config to have web view settings

### ISSUE THREAD

**Issue by BoGnY** [OpenPoGo/OpenPoGoWeb#88]
Insert in the option (userdata.js) the value (ex userPath) for "Bot path" setting, like userZoom and userFollow...
So anyone can set it for default, and when the web page is launched, bot path is show (or not, depends on setting) by default.

:)

**Comment by BobbyWibowo** [comment]
+1

**Comment by vkamathb** [comment]
+1 for bot path. 
Need to see where the bot is heading

**Comment by tvb** [comment]
➕ 1 🙏
