### ISSUE TITLE
[Not Working] Getting 404 Errors from Socket.IO?

### ISSUE THREAD

**Issue by Dekryptid** [OpenPoGo/OpenPoGoWeb#96]
Starting up using: $ python -m SimpleHTTPServer

I'm getting 404 errors from socket.io
I assume this is preventing the map to load any bot information

<img width="1259" alt="screen shot 2016-07-27 at 2 31 32 pm" src="https://cloud.githubusercontent.com/assets/6528118/17187424/29de6df6-5407-11e6-981a-13fa5c25b3b7.png">

<img width="752" alt="screen shot 2016-07-27 at 2 35 01 pm" src="https://cloud.githubusercontent.com/assets/6528118/17187482/64425728-5407-11e6-986e-50ba1f74cab3.png">

**Comment by widnyana** [comment]
try open `localhost:8000`

**Comment by Dekryptid** [comment]
I have.  The map loads.  I don't see any bots on the menu to the right below settings.  It is also not locating the bot's location / path /etc. - This used to work yesterday, prior to the socket.io implementation.  Are there instructions on how to use this with the new socket.io feature?  For example, do I have to have node installed for socket.io to work?  Does the server have to be run using node instead of python's SimpleHTTPServer?

**Comment by widnyana** [comment]
that's it, I see the same as what you see.

unfortunately, I didnt find anything yet about this new feature. seems they are quite busy developing something new, let's wait for it. :)

**Comment by meyer9** [comment]
We are working on socket.io support @ OpenPoGoBot. PokemonGoF doesn't want to support events and socket.io. If you are running the PokemonGoF bot, I'd suggest sticking to a commit before socket.io was implemented.

**Comment by Dekryptid** [comment]
Why does master have the socket.io implementation? Which branch should I use with PokemonGoF bot?

**Comment by fwoelffel** [comment]
Try using this commit https://github.com/OpenPoGo/OpenPoGoWeb/commit/b5bb1f1dbe38aa29349eaae6b85bc4a8a139a590

**Comment by Dekryptid** [comment]
Thanks! I pulled master again and git reset -hard my local repo to that commit. Now it's working again.
